version: '3.8'
services:
  db:
    image: postgres
    container_name: fetin_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fetin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fetin-db
    restart: unless-stopped
    volumes:
      - pgdata:/data/postgres
  # backend:
  #   build: 
  #     dockerfile: Dockerfile.dev
  #   container_name: fetin_backend
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   env_file:
  #     - .env
volumes:
  pgdata:
    driver: local
