name: Backend

on:
  push:
    branches: 
      - main

jobs:
  setup-db: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with: 
          node-version: 18

      - name: Install dependencies
        run: cd backend && yarn install --frozen-lockfile

      - name: Run Prisma migration
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: cd backend && yarn prisma migrate deploy

  deploy: 
    runs-on: ubuntu-latest
    needs: setup-db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with: 
          node-version: 18
      
      - name: Install dependencies
        run: cd backend && yarn install --frozen-lockfile

      - name: Install Railway 
        run: cd backend && yarn global add @railway/cli

      - name: Deploy to Railway
        run: cd backend && railway up
        env: 
          RAILWAY_TOKEN: ${{ secrets. RAILWAY_TOKEN}}